# Generated by Django 4.1.1 on 2022-10-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_discoverer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discoverer',
            old_name='title',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='discoverer',
            name='length',
        ),
        migrations.AddField(
            model_name='discoverer',
            name='name',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
