# Generated by Django 4.1.1 on 2022-10-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_title_discoverer_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('Birds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitats', to='main_app.birds')),
            ],
        ),
        migrations.DeleteModel(
            name='Discoverer',
        ),
    ]
