# Generated by Django 4.1.1 on 2022-10-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_habitat_delete_discoverer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitat',
            old_name='Birds',
            new_name='birds',
        ),
    ]
